#!/usr/bin/env php
<?php

declare(strict_types = 1);

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

/** @var Laravel\Lumen\Application $app */
$app = require __DIR__ . '/bootstrap/app.php';

/** @var Illuminate\Contracts\Console\Kernel $kernel */
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(new ArgvInput(), new ConsoleOutput()));
